---
exclude: ['README.markdown']
permalink: ':title'
sass:
  style: compressed
safe: false
title: 'Carte'
collections_dir: _articles
collections:
  texdraw_reference:
    output: true
    permalink: /:name

defaults:
  -
    scope:
      path: "texdraw"
    values:
      context: "TEXDraw"
  -
    scope:
      path: "sps"
    values:
      context: "Simple Procedural Skybox"
  -
    scope:
      path: "engine4"
    values:
      context: "Engine4"
